import "../styles/globals.css";

import "../styles/page.module.css";
import { Montserrat, Capriola } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";
import Header from "@/components/Header";
import styles from "../styles/main.module.css";

const montserrat = Montserrat({ subsets: ["latin"] });
const capriola = Capriola({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-capriola",
});

export const metadata = {
  title: "Stastiem personal app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${capriola.variable}`}>
        <div className={styles.container}>
          {/* <div> */}
          <ReduxProvider>
            <Header />
            {children}
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
