import "../styles/globals.css";
import { Montserrat } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import Header from "@/components/Header";

const montserrat = Montserrat({ subsets: ["latin"] });
// const capriola = Capriola({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-capriola",
// });

export const metadata = {
  title: "Stastiem personal application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <ReduxProvider>
          <Header />
          {children}
          <div id="modal-root"></div>
        </ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
